name: Edrig
main: com.edrig.Edrig.main
version: 0.1
author: Edrig
description: This description is a stub.
 
commands:
  yolo:
    description: This description is for template1
    usage: /yolo
    aliases: [Edrig]
  Gstart:
    description: This description is for template2
    usage: /Gstart
          /<command> do whatever template2 does
    aliases: [tmpl2]
