  name: Edrig
  main: com.edrig.Edrig.main
  version: 0.1
 
  commands:
    yolo:
    description: Notre commande.
    usage: /yolo
    permission: 
    permission-message: Vous n'avez pas la permission d'utiliser cette commande ! 

